### ISSUE TITLE
Bug: Big query plugin failed in Safari

### ISSUE THREAD

**Issue by AndrejKiri** [grafana/google-bigquery-datasource#132] opened 2022-07-08 09:27 UTC
A dashboard that works well in Firefox and Chrome is broken when opened in Safari. 

**What happened**:
When opening a dashboard ([link](https://ops.grafana.net/d/G3GhVUI7k/tech-support-top-5-kpis-dev?orgId=1)) in Chrome I get following error: 

> **GrafanaLabs-Dev Big Query plugin failed**
> Error: Invalid regular expression: invalid group specifier name Instantiating `https://ops.grafana.net/public/plugins/doitintl-bigquery-datasource/module.js` Loading `plugins/doitintl-bigquery-datasource/module`

**What you expected to happen**:
I expected that the dashboard will work well, just as it works in Firefox and Chrome. 

**How to reproduce it (as minimally and precisely as possible)**:
Open this [link](https://ops.grafana.net/d/G3GhVUI7k/tech-support-top-5-kpis-dev?orgId=1) in Safari and log in using Okta. 

**Environment**:
- Grafana version: Cloud
- Data source type & version: ? 
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Safari 15.5.
- Grafana plugins: ? 

![image](https://user-images.githubusercontent.com/4126171/177960922-4c013c68-d49c-4736-a15f-423e4c21eaa9.png)

**Comment by zoltanbedi** [comment] 2022-07-12 15:45
Hey @AndrejKiri,

You are using the old big query plugin not this one. Can you try to use this and see if the issue is still there?

**Comment by AndrejKiri** [comment] 2022-07-12 18:08
Hi @zoltanbedi, 

Unfortunately, I do not have the access rights to edit this dashboard so I cannot do it.

**Comment by chs820** [comment] 2022-07-12 18:32
@AndrejKiri - can you try viewing this dashboard? https://bi.grafana.net/d/G3GhVUI7k/tech-support-kpis?orgId=1

@chillyw - FYI if the ops.grafana.net dashboard is being deprecated, it might make sense to either delete it or hide the panels and link folks to the bi.grafana.net version

**Comment by AndrejKiri** [comment] 2022-07-12 18:46
@chs820 Sure! Here is what I can see:

 <img width="1262" alt="image" src="https://user-images.githubusercontent.com/4126171/178568788-86fd2635-b09c-4cfd-996d-ef90df0196e2.png">

The error message here is more helpful since it clearly states that the plugin is deprecated:
> **bigquery-grafanalabs-global-deprecated plugin failed**
> Error: Invalid regular expression: invalid group specifier name Instantiating `https://bi.grafana.net/public/plugins/doitintl-bigquery-datasource/module.js` Loading `plugins/doitintl-bigquery-datasource/module`

**Comment by chs820** [comment] 2022-07-12 18:50
Ohh, interesting - I didn't realize that some panels were still on the old data source. It does look like it's fixed in the new one, since the ones with the new ones are loading

**Comment by zoltanbedi** [comment] 2022-07-18 06:48
I'm going to close this issue as it is not related to this but the old plugin.

**Closed by zoltanbedi** 2022-07-18 06:48 UTC
