### ISSUE TITLE
JSON field types are unhandled

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/google-bigquery-datasource#225] opened 2023-12-20 05:40 UTC
When a table contains field type of `JSON`, plugin errors out. 

## Steps to reproduce

Query `SELECT * FROM something` where the `something` table contains a field of type **JSON** and observe the error.

**Comment by zoltanbedi** [comment] 2024-01-05 11:06
This is a duplicate of https://github.com/grafana/google-bigquery-datasource/issues/145

**Closed by zoltanbedi** 2024-01-05 11:06 UTC
