### ISSUE TITLE
Could not start plugin: "permission denied"

### ISSUE THREAD

**Issue by danjamesmay** [grafana/google-bigquery-datasource#136] opened 2022-07-27 08:58 UTC
Hi Grafana,

I have a strange issue where I am unable to install the `google-bigquery-datasource` plugin on a deployed docker instance of grafana version 8.3.2. However when I try and install it locally it works fine.

I am installing the plugin using an environmental variable.

Locally I run the following command: `docker run -d -v $(pwd)/datasource-provisioners/:/etc/grafana/provisioning/datasources/:rw -v $(pwd)/grafana.ini:/etc/grafana/grafana.ini -v $(pwd)/plugins:/var/lib/grafana/plugins -e "GF_INSTALL_PLUGINS=grafana-bigquery-datasource 1.2.0" -p 3000:3000 grafana/grafana:8.3.2`

On my deployed instance I run the same command but via a `systemd` unit.

The output locally is: 

```bash
t=2022-07-27T08:54:25+0000 lvl=dbug msg="Loading plugin" logger=plugin.loader path=/var/lib/grafana/plugins/grafana-bigquery-datasource/plugin.json
t=2022-07-27T08:54:25+0000 lvl=dbug msg="Plugin signature valid" logger=plugin.loader id=grafana-bigquery-datasource
t=2022-07-27T08:54:25+0000 lvl=dbug msg="Plugin has valid signature" logger=plugin.signature.validator id=grafana-bigquery-datasource
t=2022-07-27T08:54:25+0000 lvl=info msg="Plugin registered" logger=plugin.manager pluginId=grafana-bigquery-datasource
t=2022-07-27T08:54:25+0000 lvl=dbug msg="starting plugin" logger=plugin.initializer pluginID=grafana-bigquery-datasource path=/var/lib/grafana/plugins/grafana-bigquery-datasource/grafana-bq-ds_linux_amd64 args=[/var/lib/grafana/plugins/grafana-bigquery-datasource/grafana-bq-ds_linux_amd64]
t=2022-07-27T08:54:25+0000 lvl=dbug msg="plugin started" logger=plugin.initializer pluginID=grafana-bigquery-datasource path=/var/lib/grafana/plugins/grafana-bigquery-datasource/grafana-bq-ds_linux_amd64 pid=33
t=2022-07-27T08:54:25+0000 lvl=dbug msg="waiting for RPC address" logger=plugin.initializer pluginID=grafana-bigquery-datasource path=/var/lib/grafana/plugins/grafana-bigquery-datasource/grafana-bq-ds_linux_amd64
t=2022-07-27T08:54:25+0000 lvl=info msg="Starting BQ plugin" logger=plugin.initializer pluginID=grafana-bigquery-datasource
t=2022-07-27T08:54:25+0000 lvl=info msg=Profiler logger=plugin.initializer pluginID=grafana-bigquery-datasource enabled=false
t=2022-07-27T08:54:25+0000 lvl=dbug msg="Serving plugin" logger=plugin.initializer pluginID=grafana-bigquery-datasource plugins="[data stream diagnostics resource]"
t=2022-07-27T08:54:25+0000 lvl=dbug msg="using plugin" logger=plugin.initializer pluginID=grafana-bigquery-datasource version=2
t=2022-07-27T08:54:25+0000 lvl=dbug msg="plugin address" logger=plugin.initializer pluginID=grafana-bigquery-datasource address=/tmp/plugin107066865 network=unix
t=2022-07-27T08:54:25+0000 lvl=dbug msg="Successfully started backend plugin process" logger=plugin.initializer pluginID=grafana-bigquery-datasource
```

But on my deployed instance it fails with:

```bash
t=2022-07-26T15:22:41+0000 lvl=info msg="Plugin registered" logger=plugin.manager pluginId=grafana-bigquery-datasource
t=2022-07-26T15:22:41+0000 lvl=eror msg="Could not start plugin" logger=plugin.manager pluginId=grafana-bigquery-datasource err="fork/exec /var/lib/grafana/plugins/grafana-bigquery-datasource/grafana-bq-ds_linux_amd64: permission denied"
```

I thought there might be a permissions issue, but my entire plugins directory inside the container `/var/lib/grafana/` and `/var/lib/grafana/plugins` is owned by `grafana:root` (id's `472:0`). The plugin folder itself is unzipped with the exact same permissions as source.

Any help would be hugely appreciated!

**Comment by danjamesmay** [comment] 2022-07-27 10:43
This is also the only plugin that fails. I have tested installing many other plugins via the `grafana-cli` and they all work great.

**Comment by gabor** [comment] 2024-02-14 13:03
hi @danjamesmay sorry for not looking into this sooner!
considering grafana is now at version 10, is the problem still happening? can you reproduce it with the latest version of grafana and the latest version of the plugin? thanks!

**Comment by zoltanbedi** [comment] 2024-02-28 15:09
I'm going to close this issue as we didn't get more info on it. Please let us know if we should reopen it.

**Closed by zoltanbedi** 2024-02-28 15:09 UTC

**Comment by mehdicopter** [comment] 2024-08-05 13:52
I have the same problem
I am using a GCS bucket with FUSE and I cannot execute files so maybe it is because of that
